# Generated by Django 2.2.13 on 2020-06-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eaecontrol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Group Name')),
                ('standardEnter', models.TimeField()),
                ('standardEexit', models.TimeField()),
            ],
        ),
    ]
