# Generated by Django 2.2.13 on 2020-06-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eaecontrol', '0002_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='group',
            field=models.ForeignKey(default=None, on_delete=models.SET(None), to='eaecontrol.Group'),
            preserve_default=False,
        ),
    ]
