# Generated by Django 2.2.13 on 2020-06-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eaecontrol', '0003_person_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timing',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='timing',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
