# Generated by Django 2.2.13 on 2020-06-16 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eaecontrol', '0004_auto_20200616_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timing',
            name='date',
        ),
        migrations.RemoveField(
            model_name='timing',
            name='time',
        ),
    ]
