# Generated by Django 2.2.13 on 2020-06-16 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eaecontrol', '0006_auto_20200616_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='standardEexit',
            new_name='standardExit',
        ),
    ]
